package homework18;

public enum Position {
    ANASTESIOLOGY,
    IMMUNOLOGY,
    ALLERGY,
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    NEONATOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    ORTHOPEDIC,
    OTOLARINGOLOGY,
    UROLOGY,
    CYNECOLOGY,
    PEDIATRICS
}
